name: CI
#Trigger workflow manually, we have others like push, pull-request
on: workflow_dispatch
#Multiple triggers
#on: [workflow_dispatch, push]
jobs:
  info:
    runs-on: macos-latest
    steps:
      - name: Output Github context
        #Expressions and context objects
        run: echo "${{ toJSON(github) }}"
  build:
    runs-on: macos-latest
    steps:
      - name: Checking out project
        uses: actions/checkout@v5
      - name: building project
        run: xcodebuild -project GithubActionBootcamp.xcodeproj -scheme GithubActionBootcamp -destination 'generic/platform=iOS Simulator' clean build
  test:
    #This will wait build job to finish
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checking out project
        uses: actions/checkout@v5
      - name: Running tests
        run: xcodebuild test -project GithubActionBootcamp.xcodeproj -scheme GithubActionBootcamp -destination 'generic/platform=iOS Simulator'

