name: CI
#Trigger workflow manually, we have others like push, pull-request
on: workflow_dispatch
#Multiple triggers
#on: [workflow_dispatch, push]
jobs:
  info:
    runs-on: macos-latest
    steps:
      - name: Output Github context
        #Expressions and context objects
        run: echo "${{ toJSON(github) }}"
  build-and-test:
    runs-on: macos-latest

    env:
      SCHEME: GithubActionBootcamp
      PROJECT: GithubActionBootcamp.xcodeproj
      DERIVED_DATA: build/DerivedData
      RESULT_BUNDLE: build/TestResults.xcresult

    steps:
      - name: Checking out project
        uses: actions/checkout@v5
      # Optional but recommended: select latest stable Xcode
      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Detect simulator UDID
        id: sim
        run: |
            echo "Finding best available iPhone simulator..."

            UDID=$(xcrun simctl list devices available | \
            grep -E 'iPhone.*\(' | \
            grep -v 'unavailable' | \
            tail -n 1 | \
            grep -oE '[0-9A-F-]{36}')

            if [ -z "$UDID" ]; then
                echo "âŒ No simulator found"
                exit 1
            fi

            echo "Using simulator UDID: $UDID"
            echo "UDID=$UDID" >> $GITHUB_OUTPUT
      - name: Boot simulator
        run: |
            xcrun simctl boot "${{ steps.sim.outputs.UDID }}" || true
            xcrun simctl bootstatus "${{ steps.sim.outputs.UDID }}" -b || true
      - name: building project
        run: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination 'generic/platform=iOS Simulator' -derivedDataPath "$DERIVED_DATA" clean build CODE_SIGNING_ALLOWED=NO
      - name: Run Unit Tests
        run: xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "id=${{ steps.sim.outputs.UDID }}" -derivedDataPath "$DERIVED_DATA" -resultBundlePath "$RESULT_BUNDLE" CODE_SIGNING_ALLOWED=NO
      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: TestResults
          path: build/TestResults.xcresult
      - name: Upload app build
        uses: actions/upload-artifact@v6
        with:
          name: AppBuild
          path: build/DerivedData/Build/Products/**/*.app
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: BuildLogs
          path: build

